name: cfdi-verifier

services:
  # FastAPI application
  - name: api
    dockerfile_path: Dockerfile
    github:
      repo: 99labs-ai/cfdi-verifier
      branch: main
      deploy_on_push: true
    instance_size_slug: professional-xs
    instance_count: 1
    http_port: 8000
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: TWOCAPTCHA_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: REDIS_URL
        scope: RUN_TIME
        value: ${db-redis.REDIS_URL}

  # Celery worker for batch processing
  - name: worker
    dockerfile_path: Dockerfile
    github:
      repo: 99labs-ai/cfdi-verifier
      branch: main
      deploy_on_push: true
    instance_size_slug: professional-xs
    instance_count: 1
    run_command: celery -A celery_app worker --loglevel=info --concurrency=3
    envs:
      - key: TWOCAPTCHA_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: REDIS_URL
        scope: RUN_TIME
        value: ${db-redis.REDIS_URL}

databases:
  - name: db-redis
    engine: REDIS
    num_nodes: 1
    size: db-s-1vcpu-1gb
    version: "7"
