name: cfdi-verifier

services:
  - name: api
    dockerfile_path: Dockerfile
    github:
      repo: YOUR_GITHUB_USERNAME/cfdi-verifier
      branch: main
      deploy_on_push: true
    instance_size_slug: professional-xs
    instance_count: 1
    http_port: 8000
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: TWOCAPTCHA_API_KEY
        scope: RUN_TIME
        type: SECRET
